empleadas:
    resource: "@EmpleadasBundle/Resources/config/routing.yml"
    prefix:   /user/

PIG:
    resource: "@PIGBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /usuarios/logout
