empleadas:
    resource: "@EmpleadasBundle/Resources/config/routing.yml"
    prefix:   /

PIG:
    resource: "@PIGBundle/Resources/config/routing.yml"
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /admin/logout

logout_user:
    path: /user/logout
